Finish unfinished transactions in SentryClient
getsentry/sentry-java pull request #1209
Opened 2021-01-26 14:51 UTC by maciejwalkowiak

## :scroll: Description

Finish unfinished transactions in SentryClient

## :bulb: Motivation and Context

Fixes #1208

## :green_heart: How did you test it?

Unit tests.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] No breaking changes

2021-01-26 15:10 UTC, marandaneto commented on sentry/src/main/java/io/sentry/SentryClient.java
> +      } else {
is that right? wouldn't it be better to `finish` AND capture the transaction? or am I missing something?

2021-01-26 15:12 UTC, marandaneto commented on sentry/src/main/java/io/sentry/SentryClient.java
> +      } else {
ahhhh `finish` calls `captureTransaction` already, guess that's the trick, right?

2021-01-26 15:22 UTC, marandaneto commented
@maciejwalkowiak changelog

2021-01-26 18:55 UTC, bruno-garcia requested changes
I thought we had just agreed not to do this

2021-01-26 18:59 UTC, bruno-garcia commented
The rationale against this change is that it'll be hiding a potential programming error. A transaction is expected to be finished through `finish()` (of if captured explicitly, have its close timestamp be set explicitly via an API) so we can avoid odd bugs where transactions look normal but have been captured before they were properly finished.

2021-01-26 19:30 UTC, marandaneto commented
> I thought we had just agreed not to do this

> commented 4 hours ago

2021-01-26 20:17 UTC, maciejwalkowiak commented
PR changed to include just logging a warning. I think we don't need changelog here.

2021-01-27 08:09 UTC, marandaneto commented on sentry/src/main/java/io/sentry/ITransaction.java
> +  boolean isFinished();
should this go to `ISpan` instead?

2021-01-27 10:56 UTC, maciejwalkowiak commented on sentry/src/main/java/io/sentry/ITransaction.java
> +  boolean isFinished();
Thats true, fixed.

2021-01-27 12:15 UTC, marandaneto approved these changes

2021-01-27 13:56 UTC, merged

2021-01-27 21:29 UTC, bruno-garcia commented
> > I thought we had just agreed not to do this
> 
> commented 4 hours ago :) so even before the discussion on discord

Right, sorry about that