Hotfix release
getsentry/sentry-java pull request #3049
Opened 2023-11-13 09:07 UTC by markushi

## :scroll: Description
This is a branch for releasing `6.33.2-beta.1`, do not merge!

## :bulb: Motivation and Context
Fixes https://github.com/getsentry/sentry-java/issues/2955

## :green_heart: How did you test it?

## :pencil: Checklist

- [ ] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

## :crystal_ball: Next steps

2023-11-13 09:32 UTC, kahest requested changes

2023-11-13 09:32 UTC, kahest commented on CHANGELOG.md
> +  - This fixes SIGSEV, SIGABRT, SIGBUS crashes happening after/around the August Google Play System update, see [#2955](https://github.com/getsentry/sentry-java/issues/2955) for more details
`m`: this could get lost in the Deps section, let's move this to `### Fixes` and add a note that the fix comes in through sentry-native 0.6.7.

2023-11-13 09:56 UTC, kahest approved these changes
🚀

2023-11-15 13:00 UTC, markushi commented
Closing in favor of https://github.com/getsentry/sentry-java/pull/3053

2023-11-15 13:00 UTC, closed without merging